kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 81
    protocol: TCP
- role: worker
  extraPortMappings:
  - containerPort: 31000
    hostPort: 80
    protocol: TCP
